:Author: vansh3022
:Email:
:Date: 25/09/2021
:Revision: version#
:License: Public Domain

= Project: SIT210-Task2.1P

Displaying Name using Morris code on Arduino Nano33IoT

== Step: Installation & Working
Connect the Nano 33 IoT to the sketch uploaded in the Arduino IDE to display the Username like 'VANSH' for me 

For example:

1. Open this file in Arduino IDE 
2. Change the code according to your Username
3. Refer to the MorrisCode.png for alphabets
4. Upload the sketch and see the result

=== Folder structure

....
 SIT210-Task2.1P               => Arduino sketch folder
  ├── sketch.ino               => main Arduino file
  ├── MorrisCode.png           => Image to refer for Morris code
  └── ReadMe.adoc              => Method to work with the files
....

=== License
This project is released under a Public License.

=== Contributing
To contribute to this project please contact: 9996250931 

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name          | Part number | Quantity
| U1 | Usb Cable          | UCX00066    | 1
| A1 | Arduino Nano33IoT  | ANX00066    | 1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
